module.exports = { data: { 'trainno': 'G102',
'fmtime': '06:30',
'fmtimeps': 630, 
'totime': '12:18', 
'totimeps': 1218, 
'bgplace': '上海虹桥',
'endplace': '北京南', 
'fmcity': '上海虹桥', 
'fmcitypy': 'shanghaihongqiao',
'tocity': '北京南',
'tocitypy': 'beijingnan', 
'usedtime': '5小时48分钟', 
'usedtimeps': 348, 
'fmtype': 0,
'totype': 2,
'ifbook': 1,
'priority': 0, 
'sort': 'GD',
'note': '', 
'notetype': 0,
'notetime': '', 
'ticketstatus': { 'secseats': { 'cn': '二等座', 
    'price': 553, 
    'state': 1, 
    'seats': '99', 
    'isorder': '1', 
    'upPrice': 0, 
    'midPrice': 0, 
    'downPrice': 0 }, 
'firtseats': { 'cn': '一等座', 
    'price': 933,
    'state': 1,
    'seats': '99', 
    'isorder': '1', 
    'upPrice': 0, 
    'midPrice': 0, 
    'downPrice': 0 },
'busseats': { 'cn': '商务座',
    'price': 1748,
    'state': 1,
    'seats': '99', 
    'isorder': '1',
    'upPrice': 0, 
    'midPrice': 0, 
    'downPrice': 0 }, 
'specseats': null, 
'hardseats': null, 
'noseats': { 'cn': '无座', 
    'price': 553,
    'state': 0,
    'seats': '0', 
    'isorder': '1', 
    'upPrice': 0,
    'midPrice': 0, 
    'downPrice': 0 }, 
'hardslp': null, 
'softslp': null, 
'softsleeperdown': null, 
'advancedsoftsleeper': null, 
'dsleeperdown': null }, 
'isbook': 1, 
'bothmile': 0, 
'accbyidcard': 1, 
'trianid': 1, 
'trainflag': '0', 
'trainflagmsg': '正常车次，不受控',
'selectedSeats': { 'cn': '二等座',
    'price': 553, 
    'state': 1, 
    'seats': '99',
    'isorder': '1', 
    'upPrice': 0, 
    'midPrice': 0, 
    'downPrice': 0 } } };